"""add new models

Revision ID: 8a97a99c8a6d
Revises: 80368794e96f
Create Date: 2025-12-23 07:09:53.899259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a97a99c8a6d'
down_revision: Union[str, Sequence[str], None] = '80368794e96f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_workspace_id'), 'conversations', ['workspace_id'], unique=False)
    op.create_table('workspace_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_sections_workspace_id'), 'workspace_sections', ['workspace_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=4000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # Add workspace_id as nullable to avoid failing on existing rows without a workspace.
    # Backfill logic should be applied separately to map existing media to workspaces.
    op.add_column('media', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.add_column('media', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.drop_constraint('uq_user_file_name', 'media', type_='unique')
    op.create_index(op.f('ix_media_uploaded_by'), 'media', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_media_workspace_id'), 'media', ['workspace_id'], unique=False)
    op.create_unique_constraint('uq_workspace_file_name', 'media', ['workspace_id', 'original_filename'])
    op.drop_constraint('media_user_id_fkey', 'media', type_='foreignkey')
    op.create_foreign_key(None, 'media', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'media', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_column('media', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.create_foreign_key('media_user_id_fkey', 'media', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_workspace_file_name', 'media', type_='unique')
    op.drop_index(op.f('ix_media_workspace_id'), table_name='media')
    op.drop_index(op.f('ix_media_uploaded_by'), table_name='media')
    op.create_unique_constraint('uq_user_file_name', 'media', ['user_id', 'original_filename'])
    op.drop_column('media', 'uploaded_by')
    op.drop_column('media', 'workspace_id')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_workspace_sections_workspace_id'), table_name='workspace_sections')
    op.drop_table('workspace_sections')
    op.drop_index(op.f('ix_conversations_workspace_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
